"""
Do Not Edit this file. You may and are encouraged to look at it for reference.
"""

import unittest
import dna

class TestStrandsAreNotEmpty(unittest.TestCase):
    def test001_strandsAreNotEmptyExists(self):
        self.assertTrue('strandsAreNotEmpty' in dir(dna),
                        'Function "strandsAreNotEmpty" was not defined, check your spelling')

    def test002_neitherStrandEmpty(self):
        from dna import strandsAreNotEmpty
        self.assertTrue(strandsAreNotEmpty('aaa', 'bbb'), 'Neither the target or candidate strand were empty')

    def test003_targetStrandEmpty(self):
        from dna import strandsAreNotEmpty
        self.assertFalse(strandsAreNotEmpty('', 'aaa'), 'The target strand was empty')

    def test002_candidateStrandEmpty(self):
        from dna import strandsAreNotEmpty
        self.assertFalse(strandsAreNotEmpty('aaa', ''), 'The candidate strand was empty')

    def test005_bothStrandsEmtpy(self):
        from dna import strandsAreNotEmpty
        self.assertFalse(strandsAreNotEmpty('', ''), 'Both strands were empty')

if __name__ == '__main__':
    unittest.main()
